site_configs: &site_configs
  navbar_brand_html: >
    <a href="/" class="navbar-brand" style="padding-top: 0; padding-bottom: 0; width: 100%; height: 100%; display: flex; justify-content: center; align-items: center;">
      <img style="margin-top: 8px; height: 35px;margin-left: -20px;padding: 2px;" src="https://consensushk01.oss-cn-hongkong.aliyuncs.com/public/logo.svg" alt="consensushk-logo"/>
    </a>
  navbar_html: >
    <li><a href="/topics/new">發起討論</a>
  wiki_index_html: >
    <div>Wiki 首頁</div>
  wiki_sidebar_html: >
    <strong>關於</strong>
    <ul>
      <li><a href="/wiki/about">關於 ConsensusHK</a></li>
    </ul>
  footer_html: >
    <div class="media">
      <div class="media-left" style="padding: 5px 25px 0 10px;">
        <img class="media-object" src="https://consensushk01.oss-cn-hongkong.aliyuncs.com/public/logo-color.svg" style="width: 60px;">
      </div>
      <div class="media-body">
        <div class="links">
          <a href="/wiki/about">關於</a> / <a href="/status" target="_blank">Status</a> / <a href="/users">活躍會員</a> / <a href="/teams">組織</a> / <a href="https://yuque.com/ruby-china/api/getting-started">API</a> / <a href="/wiki/contributors">貢獻者</a>
        </div>
        <div class="copyright" style="margin-top:5px">
          <img class="media-object" src="https://consensushk01.oss-cn-hongkong.aliyuncs.com/public/logotype.svg" style="height: 12px;display: inline-block;padding: 0 2px 2px 0;">是由眾多愛好者共同發起并維護的區塊鏈技術中文社區，本站使用 <a href="https://gethomeland.com">Homeland</a> 構建，並採用 Docker 部署。
        </div>
        <div class="links" style="margin-top:5px">
          <span class="socials">
         <a href="http://github.com/consensushk" target="_blank" rel="nofollow" title="本站在 GitHub 上面的開源內容"><i class="fa fa-github"></i></a>
         <a href="http://twitter.com/consensushk" target="_blank" rel="nofollow" title="本站的 Twitter 賬號"><i class="fa fa-twitter"></i></a>
         <a href="/topics/feed" target="_blank" rel="nofollow"><i class="fa fa-rss"></i></a>
         </span>
          <a href="?locale=zh-CN" rel="nofollow" style="margin-left: 20px">簡體中文</a> / <a href="?locale=zh-TW" rel="nofollow">正體中文</a> / <a href="?locale=en" rel="nofollow">English</a>
        </div>
      </div>
    </div>
  after_topic_html: ""
  before_topic_html: ""
  topic_index_sidebar_html: ""
  site_index_html: "下面列出了篩選出的區塊鏈相關網站，如你有想推薦的網站，請幫忙補充。"
  custom_head_html: >
    <link rel="dns-prefetch" href="//assets.your-host.com">
    <meta name="publisher" content="共識香港 ConsensusHK">
    <meta property="og:site_name" content="共識香港 ConsensusHK" />
    <meta property="og:locale" content="zh_HK">
    <meta property="og:locale:alternate" content="zh_HK">
    <meta property="og:locale:alternate" content="zh_TW">
    <meta property="og:locale:alternate" content="zh_CN">
    <meta name="description" content="共識相關是一個於香港發起的區塊鏈技術社區。我們以深挖區塊鏈底層技術和應用場景為特色，同時觀察和解析技術走向與政府監管，致力於以去中心化的社區模式連接以人做為的節點，為本地區塊鏈行業發展與項目落地助力。">
    <meta name="keywords" content="共識香港,consensushk,共識,consensus,香港,Hong Kong,比特幣,bitcoin,以太坊,etheruem,區塊鏈,blockchain,數字貨幣,crypto,cryptocurrency,技術,社區,技術社區,香港,台灣,中國,深圳,大灣區,金融,香港區塊鏈,本地,國際,最新">
  node_ids_hide_in_topics_index: ""
  new_topic_dropdown_node_ids: ""
  ban_words_on_reply: >
    mark
    收藏
    顶
    赞
    up
  tips: >
    提示1
    提示2
  newbie_notices: >
    <p>為提高技术社區質量，防止新人重複發帖提問，新用戶需要達到下面條件才可發帖：</p>
    <ol style="color:#ad2b2d;">
      <li>註冊時間超過一天；</li>
      <li>回帖數量必須達到 5 帖以上；</li>
    </ol>
    <p>請在新人階段多瀏覽，看看老用戶是如何在 ConsensusHK 技術社區裡面分享與解決問題的。</p>
  reject_newbie_reply_in_the_evening: false
  apns_pem: ""
  blacklist_ips: ""
  newbie_limit_time: 86400

defaults: &defaults
  <<: *site_configs
  app_name: "<%= ENV['app_name'] %>"
  modules: "<%= ENV['modules'] || 'all'  %>"
  profile_fields: "<%= ENV['profile_fields'] || 'all' %>"
  domain: "<%= ENV['domain'] %>"
  https: <%= ENV['https'] || 'true' %>
  default_locale: "<%= ENV['default_locale'] || 'zh-CN' %>"
  auto_locale: <%= ENV['auto_locale'] || 'false' %>
  admin_emails: <%= ENV['admin_emails'] || 'admin@admin.com' %>
  google_analytics_key: "<%= ENV['google_analytics_key'] %>"
  asset_host: "<%= ENV['asset_host'] %>"
  <% if ENV['rack_attack.limit'] == 'true' %>
  rack_attack:
    limit: <%= ENV['rack_attack.limit'] %>
    period: <%= ENV['rack_attack.period'] %>
  <% end %>
  upload_provider: "<%= ENV['upload_provider'] %>" # can be  upyun/aliyun
  upload_access_id: "<%= ENV['upload_access_id'] %>" # or username
  upload_access_secret: "<%= ENV['upload_access_secret'] %>" # or upyun password
  upload_bucket: "<%= ENV['upload_bucket'] %>"
  upload_url: "<%= ENV['upload_url'] %>"
  upload_aliyun_internal: <%= ENV['upload_aliyun_internal'] == 'true' %>
  upload_aliyun_area: "<%= ENV['upload_aliyun_area'] %>"
  mailer_provider: "<%= ENV['mailer_provider'] %>"
  mailer_sender: "<%= ENV['mailer_sender'] %>"
  mailer_options:
    <% if ENV['mailer_provider'] == 'postmark' %>
    api_key: '<%= ENV['mailer_options.api_key'] %>'
    <% else %>
    address: '<%= ENV['mailer_options.address'] %>'
    port: <%= ENV['mailer_options.port'] %>
    domain: '<%= ENV['mailer_options.domain'] %>'
    user_name: '<%= ENV['mailer_options.user_name'] %>'
    password: '<%= ENV['mailer_options.password'] %>'
    authentication: '<%= ENV['mailer_options.authentication'] %>'
    enable_starttls_auto: <%= ENV['mailer_options.enable_starttls_auto'] %>
    <% end %>
  sso:
    <% if ENV['sso.enable_provider'] != 'true' %>
    enable: <%= ENV['sso.enable'] || false %>
    <% else %>
    enable_provider: <%= ENV['sso.enable_provider'] || false %>
    <% end %>
    url: '<%= ENV['sso.url'] %>'
    secret: '<%= ENV['sso.secret'] %>'
  github_token: "<%= ENV['github_token'] %>"
  github_secret: "<%= ENV['github_secret'] %>"

production:
  <<: *defaults
